version: '3'

services:
  postgres:
    image: enubia/donate-gifts-dev-db
    restart: always
    environment:
      POSTGRES_DB: '${POSTGRES_DATABASE}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
